POST http://localhost:8000/api/register HTTP/1.1
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@admin.tg",
    "password":"Admin0000",
    "confirm_password":"Admin0000"
}

# eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9yZWdpc3RlciIsImlhdCI6MTYyMDEzMzgxNSwiZXhwIjoxNjIwMTM3NDE2LCJuYmYiOjE2MjAxMzM4MTYsImp0aSI6IlhweE5qNVJzeFE3RTl2NVEiLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.D2EOYzqTk6Pu4CPU003EZYYFY21RMnCSQAV1bpU0-3k

###

POST http://localhost:8000/api/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin@admin.tg",
    "password":"Admin0000"
}

# eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYyMDEzMzg5MiwiZXhwIjoxNjIwMTM3NDkyLCJuYmYiOjE2MjAxMzM4OTIsImp0aSI6InNkOUV6U1UyOEladjZ6RFYiLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.yHiXiHqlygXg9baIotXzE_r_uDbUFBGiNThdkT0HG9U

###

POST http://localhost:8000/api/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYyMDEzMzg5MiwiZXhwIjoxNjIwMTM3NDkyLCJuYmYiOjE2MjAxMzM4OTIsImp0aSI6InNkOUV6U1UyOEladjZ6RFYiLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.yHiXiHqlygXg9baIotXzE_r_uDbUFBGiNThdkT0HG9U

{
    "title":"check",
    "details":"ok"
}


###

GET url HTTP/1.1